require "lsp"
require "dap-config.init"
--[[ require "plugin.cmp_config" ]]
require "plugin.coq"
require "plugin.trouble"
require "plugin.treesitter"
require "plugin.autopairs"
require "plugin.lualine"
require "plugin.comment"
-- require"plugin.bufferline"
require "plugin.tabby"
require "plugin.surround"
