--[[ require "plugin.coq" ]]
require "lsp"
require "dap-config.init"
require "plugin.cmp_config"
require "plugin.trouble"
require "plugin.treesitter"
require "plugin.autopairs"
require "plugin.lualine"
require "plugin.comment"
-- require"plugin.bufferline"
require "plugin.tabby"
require "plugin.surround"
require "plugin.hex"
