require"lsp.init".setup()
-- require"dap.init"
require"plugin.cmp_config"
require"plugin.trouble"
require"plugin.treesitter"
require"plugin.autopairs"
require"plugin.lualine"
require"plugin.comment"
-- require"plugin.bufferline"
require"plugin.tabby"
