wallpaper {
    monitor = DP-3
    path = ~/.local/share/wallpapers/pexels-cede-joey-2050570-29546721.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-4
    path = ~/.local/share/wallpapers/lavender-fields-5120x2880-21314.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-5
    path = ~/.local/share/wallpapers/lavender-fields-5120x2880-21314.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-6
    path = ~/.local/share/wallpapers/katelyn-g-L4jXDAzSiFU-unsplash.jpg
    fit_mode = cover
}

wallpaper {
    monitor =
    path = ~/.local/share/wallpapers/milky-way-starry-sky-night-mountains-lake-reflection-cold-5k-5760x3840-287.jpg
    fit_mode = cover
}

splash=false
