#!/bin/bash

if [[ $XDG_CURRENT_DESKTOP == KDE ]]
then
  kquitapp5 plasmashell && kstart5 plasmashell &
fi

if [[ $(qtile cmd-obj -o cmd -f status) == \'OK\' ]]
then
  nitrogen --restore
  qtile cmd-obj -o cmd -f reload_config
fi
